### ISSUE TITLE
Change favicon and title

### ISSUE THREAD

**Issue by Nordico-team** [siigdev/Travelbunny-Web#7]
The atual favicon of the webpage is the react favicon.
And the title is "Nordico.tech"
Those are not so good in my opinion for the project.
For example, a favicon that I suggest is this one: [https://cdn.glitch.com/a4f85e36-d0a0-4d58-a277-06994c25436f%2F281ea486-c589-4511-bdd4-967988ac42ac_Webp.net-resizeimage.png?request=githubisisue](https://cdn.glitch.com/a4f85e36-d0a0-4d58-a277-06994c25436f%2F281ea486-c589-4511-bdd4-967988ac42ac_Webp.net-resizeimage.png?request=githubisisue)
And a title, simple: Just "Nordico" (Without the quotes)
By Tiago Rangel de Sousa

**Comment by siigdev** [comment]
I agree. However, this is not exactly necessary until we get a graphics designer to create a custom favicon. This is easily changed within the /public/ folder.

**Comment by Nordico-team** [comment]
Thanks

**Comment by tiagorangel2011** [comment]
Title changed
